# Generated by Django 4.2.7 on 2023-11-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_projects_skills_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='skill1',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('html5', 'HTML5'), ('css3', 'CSS3'), ('bash', 'Bash'), ('javascript', 'Javascript')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='skill2',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('html5', 'HTML5'), ('css3', 'CSS3'), ('bash', 'Bash'), ('javascript', 'Javascript')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='skill3',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('html5', 'HTML5'), ('css3', 'CSS3'), ('bash', 'Bash'), ('javascript', 'Javascript')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='skill4',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('html5', 'HTML5'), ('css3', 'CSS3'), ('bash', 'Bash'), ('javascript', 'Javascript')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='skill5',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('html5', 'HTML5'), ('css3', 'CSS3'), ('bash', 'Bash'), ('javascript', 'Javascript')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='skill6',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('html5', 'HTML5'), ('css3', 'CSS3'), ('bash', 'Bash'), ('javascript', 'Javascript')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_created',
            field=models.DateField(blank=True, default='2023-10-23', null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, default='default description  -  jkfhbsvliughflkjwshbkuifgbvlsghglifvbksuyhrglbwelsuihgbliuhwliuhgri', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='git_link',
            field=models.URLField(blank=True, default='https://www.google.com/', null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
