# Generated by Django 4.2.7 on 2023-11-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_blog_project_delete_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date_written',
        ),
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(default='test content'),
        ),
        migrations.AddField(
            model_name='blog',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
