# Generated by Django 4.2.7 on 2023-11-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_blog_date_written_blog_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.TextField(blank=True, default='default description  -  jkfhbsvliughflkjwshbkuifgbvlsghglifvbksuyhrglbwelsuihgbliuhwliuhgri', max_length=100, null=True),
        ),
    ]
